# encoding: utf-8
# frozen_string_literal: true

#
# Cookbook Name:: ec2-net-utils
# Library:: resource/ec2-net-utils/rhel
#
# Copyright 2017, Socrata, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require_relative '../ec2_net_utils'

class Chef
  class Resource
    class Ec2NetUtils < Resource
      # A RHEL implementation of the ec2_net_utils resource.
      #
      # @author Jonathan Hartman <jonathan.hartman@socrata.com>
      class Rhel < Ec2NetUtils
        resource_name :ec2_net_utils_rhel
        provides :ec2_net_utils, platform_family: 'rhel'

        #
        # RHEL7 has disabled network device hotplugging.
        #
        def hotplug_support
          node['platform_version'].to_i < 7
        end

        #
        # RHEL configs are just the networking device configs. Routes and
        # dhclient are managed separately.
        #
        def dev_config_format
          <<-EOH.gsub(/^ +/, '').strip
            # This file is automatically generated.
            # Any changes to it will be overwritten.
            DEVICE=${INTERFACE}
            BOOTPROTO=dhcp
            ONBOOT=yes
            TYPE=Ethernet
            USERCTL=yes
            PEERDNS=no
            IPV6INIT=yes
            DHCPV6C=yes
            DHCPV6C_OPTIONS=-nw
            PERSISTENT_DHCLIENT=yes
            HWADDR=${HWADDR}
            DEFROUTE=no
            EC2SYNC=yes
          EOH
        end

        #
        # RHEL device configs live in the network-scripts dir.
        #
        def dev_config_path
          "#{dev_config_dir}/ifcfg-${INTERFACE}"
        end

        #
        # The network-scripts dir also includes route configs.
        #
        def dev_route_path
          "#{dev_config_dir}/route-${INTERFACE}"
        end

        #
        # ...and route6 configs.
        #
        def dev_route6_path
          "#{dev_config_dir}/route6-${INTERFACE}"
        end

        #
        # RHEL supports each device getting its own dhclient config.
        #
        def dev_dhclient_path
          '/etc/dhcp/dhclient-${INTERFACE}.conf'
        end

        #
        # RHEL network device configs live in the network-scripts dir.
        #
        def ec2ifscan_dev_path
          "#{dev_config_dir}/ifcfg-${dev##*/}"
        end

        #
        # On RHEL systems, DHCP helper scripts must end in .sh.
        #
        def ec2dhcp_script_path
          ::File.join(dhclient_scripts_dir, 'ec2dhcp.sh')
        end

        #
        # RHEL's dhclient supports scripts in dhclient.d.
        #
        def dhclient_scripts_dir
          '/etc/dhcp/dhclient.d'
        end

        #
        # RHEL systems have the same network-scripts dir as Amazon Linux so can
        # use the same path. Scripts and devices go in the same dir.
        #
        def network_scripts_dir
          '/etc/sysconfig/network-scripts'
        end
        alias dev_config_dir network_scripts_dir
      end
    end
  end
end
