---
driver:
  name: ec2
  shared_credentials_profile: staging
  region: us-west-2
  aws_ssh_key_id: shared-bootstrap
  subnet_id: subnet-c174d9b6

transport:
  ssh_key: ~/.ssh/aws_bootstrap

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7.3
  - name: centos-6.9
  - name: ubuntu-16.04-chef-12
    provisioner:
      require_chef_omnibus: 12
  - name: ubuntu-14.04-chef-12
    provisioner:
      require_chef_omnibus: 12
  - name: centos-7.3-chef-12
    provisioner:
      require_chef_omnibus: 12
  - name: centos-6.9-chef-12
    provisioner:
      require_chef_omnibus: 12

suites:
  - name: default
    run_list:
      - recipe[ec2-net-utils]
    verifier:
      inspec_tests:
        - test/smoke/default
