---
driver:
  name: ec2
  region: <%= ENV['AWS_REGION'] %>
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  subnet_id: <%= ENV['AWS_SUBNET_ID'] %>

transport:
  ssh_key: <%= ENV['AWS_SSH_KEY_FILE'] %>

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-8
  - name: centos-7
  - name: centos-6

suites:
  - name: default
    run_list:
      - recipe[ec2-net-utils_test]
    verifier:
      inspec_tests:
        - test/smoke/default
  - name: chef-12
    run_list:
      - recipe[ec2-net-utils_test]
    verifier:
      inspec_tests:
        - test/smoke/default
    provisioner:
      require_chef_omnibus: 12
