language: ruby

branches:
  only:
    - master

sudo: required

services:
  - docker

install:
  - curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -P chefdk
  - chef exec bundle install --without=development integration

script:
  - chef exec bundle exec rake && chef exec bundle exec kitchen test -c 2
